### ISSUE TITLE
Setup deploy infra for new Indexer

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/fuel-explorer#330]
# Tasks

- [x] Finish Kubernetes configuration on deployments repo
- [x] Improve NodeJS project to have better concurrency performance
    - [x] Improve queue system using PgBoss
    - [x] Use PM2 to split processes and avoid single thread problems
    - [x] Use xstate to handle the limit of execution in memory
    - [x] Use NodeJS worker to have concurrency for add transactions
